[build]
  publish = "build/site/"
  command = "node_modules/.bin/antora --generator antora-site-generator-lunr --stacktrace --fetch --html-url-extension-style=indexify antora-playbook.yml"

[build.environment]
  NODE_VERSION = "14"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"
  DOCSEARCH_ENABLED = "true"
  DOCSEARCH_ENGINE = "lunr"

[context.deploy-preview]
  command = "node_modules/.bin/antora --generator antora-site-generator-lunr --stacktrace --fetch --html-url-extension-style=indexify --url $DEPLOY_PRIME_URL antora-playbook.yml"
